# Generated by Django 5.2 on 2025-04-25 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('duration', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('genre', models.CharField(blank=True, max_length=100)),
                ('director', models.CharField(blank=True, max_length=100)),
                ('release_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='show',
            name='description',
        ),
        migrations.RemoveField(
            model_name='show',
            name='title',
        ),
        migrations.AddField(
            model_name='show',
            name='movie',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='shows', to='booking.movie'),
            preserve_default=False,
        ),
    ]
