services:
  web:
    build: .
    command: gunicorn ticket_booking_system.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    environment:
      - DEBUG=1
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ticketbooking
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
